const styles = {
  ratingCard: {
    backgroundColor: "white",
    borderRadius: 16,
    padding: 2,
    shadow: 1,
    width: 150,
    height: 100,
    borderWidth: 1,
    borderColor: "grey",
  },
  ratingCards: {
    backgroundColor: "white",
    borderRadius: 16,
    padding: 2,
    shadow: 1,
    width: 150,
    height: 75,
    borderWidth: 2,
    borderColor: "grey",
  },
  ratintext: {
    fontSize: 16,
    paddingBottom: 4,
    fontWeight: "bold",
  },
  reviewtext: {
    fontSize: 12,
    paddingBottom: 4,
  },
  buttonAdd: {
    backgroundColor: "white",
    borderRadius: 10,
    padding: 4,
    width: 75,
    height: 75,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#149873",
  },
  buttonHistoryContainer: {
    alignItems: "flex-end",
    marginRight: 10,
  },
  buttonHistory: {
    backgroundColor: "#149873",
    borderRadius: 16,
    padding: 4,
    width: 150,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  expertCard: {
    backgroundColor: "white",
    borderRadius: 8,
    // borderWidth: 1,
    // borderColor: "grey",
    padding: 4,
    marginY: 2,
    shadow: 1,
  },
  expertCardText: {
    fontWeight: "bold",
    fontSize: 12,
    paddingBottom: 4,
  },
  expertCardDiscription: {
    fontSize: 10,
    paddingBottom: 4,
  },
};

export default styles;
