export const styles = {
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },

  photoSlider: {
    width: "95%",
    height: 200,
    borderRadius: 16,
  },

  ExpertDiscription: {
    padding: 20,
    margin: 10,
    width: "90%",
    marginTop: 20,
  },
  Availability: {
    padding: 20,
    margin: 10,
    width: "90%",
    marginTop: 20,
  },
  button: {
    padding: 10,
    width: "60%",
    justifyContent: "center",
    borderRadius: 34,
    margin: 10,
  },
  buttonContent: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 10,
    width: "100%",
    color: "white",
  },
  ExpertDetails: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "gray",
    backgroundColor: "white",
    padding: 16,
    margin: 16,
    width: "90%",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 5,
  },
  label: {
    fontWeight: "bold",
    marginRight: 10,
  },
  value: {
    margin: 5,
  },
  ratingCard: {
    backgroundColor: "white",
    borderRadius: 16,
    padding: 2,
    shadow: 1,
    width: 150,
    height: 100,
    borderWidth: 1,
    borderColor: "gray.200",
  },
  ratintext: {
    fontSize: 16,
    paddingBottom: 4,
    fontWeight: "bold",
  },
  reviewtext: {
    fontSize: 12,
    paddingBottom: 4,
  },
  buttonAdd: {
    backgroundColor: "white",
    borderRadius: 10,
    padding: 4,
    width: 75,
    height: 75,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#149873",
  },
  buttonHistoryContainer: {
    alignItems: "flex-end",
    marginRight: 10,
  },
  buttonHistory: {
    backgroundColor: "#149873",
    borderRadius: 16,
    padding: 4,
    width: 150,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  expertCard: {
    backgroundColor: "white",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "gray.200",
    padding: 4,
    marginY: 2,
    shadow: 1,
  },
  expertCardText: {
    fontWeight: "bold",
    fontSize: 12,
    paddingBottom: 4,
  },
  expertCardDiscription: {
    fontSize: 10,
    paddingBottom: 4,
  },
  ratingsFrame: {
    flex: 1,
    padding: 8,
    marginTop: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "gray",
  },
  ratingsFrameText: {
    fontSize: 14,
    paddingLeft: 16,
    paddingBottom: 8,
    paddingTop: 8,
    fontStyle: "italic",
  },
  dateAndTimeText: {
    fontSize: 16,
    fontWeight: 500,
  },
  jobAmount: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#149873",
  },
};
